---
#####Ubuntu 20 系统初始化######
#用法 : ansible-playbook ubuntu20_init.yml -i 1.1.1.1,2.2.2.2,
#用法 : 修改 /etc/ansible/hosts [ubuntu20]中的主机列表  ansible-playbook ubuntu20_init.yml
#- hosts: 1.1.1.1
- hosts: ubuntu22
  remote_user: root
  #become: yes
  #become_method: su
  vars_prompt:
    - name: "root_password"
      prompt: "请输入新的root密码"
      private: yes
      encrypt: "md5_crypt"
      confirm: yes
      salt_size: 7
  vars:
    - ansible_connection: smart
    - ansible_port: 22 
    - ansible_user: root 
    - ansible_ssh_pass: qwe123
    - ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - { role: addbanner, env: '{{ hostname_prefix }}'}
    - { role: dns, env: '{{ hostname_prefix }}' }
    - { role: apt, env: '{{ hostname_prefix }}' }
    - { role: packages }
    - { role: disk }
    - { role: hostname }
    - { role: hosts }
    - { role: adduser, env: '{{ hostname_prefix }}' }
    - { role: sshd, env: '{{ hostname_prefix }}' }
    - { role: ntp, env: '{{ hostname_prefix }}' }
    - { role: iptables, env: '{{ hostname_prefix }}'  }
    - { role: ulimit }
    - { role: sysctl }
    - { role: audit }
    - { role: systemd, env: '{{ hostname_prefix }}'  }
    - { role: logrotate }
    - { role: vimrc }
    - { role: filebeat, env: '{{ hostname_prefix }}' }
    - zabbix-client
    - salt-minion
    - { role: chgRootPass, password: '{{ root_password }}' }
