# TiDB Configuration.

# TiDB server host.
host = "0.0.0.0"

# tidb server advertise IP.
advertise_address = ""

# TiDB server port.
port = 4000

# path = ""

[inc]
check_autoincrement_datatype            =false
check_autoincrement_init_value          =false
check_autoincrement_name                =false
check_column_comment                    =false
check_column_default_value              =false
check_column_position_change            =false
check_column_type_change                =true                         
check_dml_limit                         =true                                     
check_dml_orderby                       =true                                     
check_dml_where                         =true                                     
check_identifier                        =false
check_index_prefix                      =false
check_insert_field                      =true                                     
check_primary_key                       =true                                     
check_table_comment                     =true                                      
check_timestamp_default                 =false
check_timestamp_count                   =false                                      
enable_autoincrement_unsigned           =false
enable_blob_type                        =true
enable_blob_not_null                    =true
enable_column_charset                   =false
enable_drop_database                    =false
enable_drop_table                       =true
enable_enum_set_bit                     =true
enable_fingerprint                      =false
enable_foreign_key                      =true
enable_json_type                        =false
enable_identifer_keyword                =false                                     
enable_not_innodb                       =false                                     
enable_nullable                         =true
enable_null_index_name                  =false
enable_orderby_rand                     =false
enable_partition_table                  =false
enable_pk_columns_only_int              =false
enable_select_star                      =false
enable_set_charset                      =false
enable_set_collation                    =true
enable_set_engine                       =true
disable_types                           =""
max_char_length                         =0
max_insert_rows                         =0                                 
max_keys                                =5                                     
max_key_parts                           =5                                     
max_update_rows                         =5000
max_primary_key_parts                   =1                                      
max_allowed_packet                      =33554432
merge_alter_table                       =false
check_float_double                      =true
support_charset                         ="utf8,utf8mb4,utf8mb3"
support_collation                       ="utf8_bin,utf8_general_ci,utf8mb4_general_ci,utf8mb3_general_ci"


backup_host = "mysql"
backup_port = 3306
backup_user = "root"
backup_password = "123qwe"


# 设置执行SQL时，会话变量
# 0 表示不做操作，基于远端数据库【默认值】
# > 0 值表示，会话在执行SQL 时获取锁超时的时间
lock_wait_timeout = 10

# 安全更新是否开启.
# -1 表示不做操作,基于远端数据库 [默认值]
# 0  表示关闭安全更新
# 1  表示开启安全更新
sql_safe_updates = -1

# lang = "en-US"
lang = "zh-CN"

# 是否记录全量日志
general_log = false

# 开启统计功能
enable_sql_statistic = true


[inc_level]
er_cant_set_engine = 2
er_cant_set_collation = 2
er_table_must_have_comment = 2
er_column_have_no_comment = 2
er_table_must_have_pk = 2
er_index_name_idx_prefix = 1
er_index_name_uniq_prefix =  1
er_autoinc_unsigned = 2
er_alter_table_once = 2
er_pk_too_many_parts = 2

[osc]
osc_on = false
osc_min_table_size = 16
osc_print_none = false
osc_bin_dir = "/usr/local/bin"

[ghost]

ghost_on = false
ghost_allow_on_master = true
ghost_assume_rbr = true
ghost_chunk_size = 1000
ghost_concurrent_rowcount = true
ghost_cut_over = "atomic"
ghost_cut_over_lock_timeout_seconds = 3
ghost_default_retries = 60
ghost_heartbeat_interval_millis = 500
ghost_max_lag_millis = 1500
ghost_approve_renamed_columns = true
ghost_exponential_backoff_max_interval = 64
ghost_dml_batch_size = 10

[log]
# Log level: debug, info, warn, error, fatal.
level = "error"
# Log format, one of json, text, console.
format = "console"
