test:
  hosts:
    2.2.2.2:
    3.3.3.3:
    test01:
      ansible_host: 8.8.8.8
      http_port: 80
    test02: 
      ansible_host: 1.1.1.1
      http_port: 443
  vars:
    ansible_user: root
    ansible_ssh_pass: xxx
