- name: Simple Template Playbook
  hosts: template
  remote_user: yakir
  become: yes
  tasks:
    - name: Test
      ansible.builtin.ping:
      #ansible.builtin.debug:
      #  msg: Hello world

    - name: Debug
      debug:
        #msg: "debug test"
        var: k1
      # get host_vars or group_vars
      #when: template_host_var == "yes"
      when: template_group_var == "yes"

    - name: import tasks
      import_tasks: Debian.yml
      when: ansible_os_family == "Debian"
    - name: include tasks
      include_tasks: "{{item}}.yaml"
      with_items:
        - i1
        - i2

    - name: when syntax
      command: /bin/echo hello
      when: ansible_os_family == 'Debian'

    - name: loop syntax
      user: name= state=present groups=
      with_items:
        - { name: 'user1', groups: 'group1'}
        - { name: 'user2', groups: 'group2'}

    - name: custom fact
      debug:
        var: ansible_local.forbidden.forbid

  roles:
    - role: redis
      vars:
        config: redis.conf
        port: 6379

