apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Revision }}-configmap
  labels:
    {{- template "yakir-chart.labels" . }}
{{ include "yakir-chart.app" . | indent 4 }}
data:
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | indent 4 }}
  {{- end }}
  release_name: {{ .Release.Name }}
  release_revision: {{ .Release.Revision }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
{{ include "yakir-chart.app" . | indent 2 }}
