---
- name: ali apt sources config
  block:
    - name: ali add sources.list
      copy: src=ali_sources.list dest=/etc/apt/sources.list

    - name: apt update
      shell: apt update && apt list --upgradable

  when:  hostname_prefix  == "ubuntu20"
