- name: Download Filebeat From Source Server
  get_url: url=http://1.1.1.1:8080/elk/filebeat-7.3.1-amd64.deb dest=/opt/ mode=0644
  when: env == 'ali'

- name: Install And Config Filebeat
  block:
    - name: Install Filebeat rpm From Local File
      shell: dpkg -i /opt/filebeat-7.3.1-amd64.deb
      when: ansible_distribution_major_version == '20'    
    
    - name: Delete Local RPM
      file: path=/opt/filebeat-7.3.1-amd64.deb state=absent
    
    - name: Upload Filebeat.yml
      copy: src=wtt_filebeat.yml dest=/etc/filebeat/filebeat.yml owner=root group=root mode=0600
      when: env == 'ali'
      notify: Start Filebeat
