---
# tasks file for addbanner
- name: Add Login Banner
  copy: src=system_info.sh dest=/etc/profile.d/system_info.sh owner=root group=root mode=0644
  when: env == "ali"

- name: Add System Alias
  copy: src=rmcmd.sh dest=/etc/profile.d/rmcmd.sh owner=root group=root mode=0644

- name: Add rm Alias to /etc/bashrc
  lineinfile:
    dest: /etc/bash.bashrc
    line: "alias rm='rm_cmd $@'"

- name: Add sortcpu Alias to /etc/bash.bashrc 
  lineinfile:
    dest: /etc/bash.bashrc
    line: "alias sortbycpu='ps -Ao pcpu,comm,pid,user,etime,pmem,lstart --sort=-pcpu |column -t'"

- name: Add sortmem Alias to /etc/bash.bashrc 
  lineinfile:
    dest: /etc/bash.bashrc
    line: "alias sortbymem='ps -eo pmem,comm,pid,rss,vsz,user --sort -rss |column -t'"

- name: Add PS1 color to /etc/bash.bashrc 
  blockinfile:
    path: /etc/bash.bashrc 
    block: |
      export PS1='\[\e[37;1m\][\[\e[35;1m\]\u\[\e[32;1m\]@\[\e[34;1m\]\h \[\e[31;1m\]\w]\$\[\e[m\] '
